# Ref: https://github.com/DandyDeveloper/charts/blob/master/charts/redis-ha/values.yaml
redis-ha:
  # -- Enables the Redis HA subchart
  enabled: true
  ## Prometheus redis-exporter sidecar
  exporter:
    # -- Enable Prometheus redis-exporter sidecar
    enabled: true
    serviceMonitor:
      enabled: true
      labels:
        release: # system provided
  persistentVolume:
    # -- Configures persistence on Redis nodes
    enabled: true
  # -- Whether the Redis server pods should be forced to run on separate nodes.
  hardAntiAffinity: true
  # -- Number of redis master/slave
  replicas: 1
  redis:
    config:
      min-replicas-to-write: 0
    # -- CPU/Memory for master/slave nodes resource requests/limits
    resources:
      requests:
        cpu: 500m
        ephemeral-storage: 50Mi
        memory: 1Gi
      limits:
        cpu: 750m
        ephemeral-storage: 2Gi
        memory: 1536Mi