ingress-nginx:
  enabled: true
  controller:
    extraArgs:
      enable-ssl-passthrough: true
    admissionWebhooks:
      enabled: false
    service:
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
        service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
        service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: "/healthz"
        service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: "10254"
        service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: "HTTP"
      external: 
        enabled: true
      internal:
        enabled: false
        # annotations:
        #   service.beta.kubernetes.io/aws-load-balancer-scheme: "internal"
cert-manager:
  enabled: true
  crds:
    enabled: true
    keep: false